// Code generated by Kitex v0.10.3. DO NOT EDIT.

package asset

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	ucenter "grpc_common/kitex_gen/ucenter"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	FindWalletBySymbol(ctx context.Context, Req *ucenter.AssetReq, callOptions ...callopt.Option) (r *ucenter.MemberWallet, err error)
	FindWallet(ctx context.Context, Req *ucenter.AssetReq, callOptions ...callopt.Option) (r *ucenter.MemberWalletList, err error)
	ResetWalletAddress(ctx context.Context, Req *ucenter.AssetReq, callOptions ...callopt.Option) (r *ucenter.AssetResp, err error)
	FindTransaction(ctx context.Context, Req *ucenter.AssetReq, callOptions ...callopt.Option) (r *ucenter.MemberTransactionList, err error)
	GetAddress(ctx context.Context, Req *ucenter.AssetReq, callOptions ...callopt.Option) (r *ucenter.AddressList, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAssetClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAssetClient struct {
	*kClient
}

func (p *kAssetClient) FindWalletBySymbol(ctx context.Context, Req *ucenter.AssetReq, callOptions ...callopt.Option) (r *ucenter.MemberWallet, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FindWalletBySymbol(ctx, Req)
}

func (p *kAssetClient) FindWallet(ctx context.Context, Req *ucenter.AssetReq, callOptions ...callopt.Option) (r *ucenter.MemberWalletList, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FindWallet(ctx, Req)
}

func (p *kAssetClient) ResetWalletAddress(ctx context.Context, Req *ucenter.AssetReq, callOptions ...callopt.Option) (r *ucenter.AssetResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ResetWalletAddress(ctx, Req)
}

func (p *kAssetClient) FindTransaction(ctx context.Context, Req *ucenter.AssetReq, callOptions ...callopt.Option) (r *ucenter.MemberTransactionList, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FindTransaction(ctx, Req)
}

func (p *kAssetClient) GetAddress(ctx context.Context, Req *ucenter.AssetReq, callOptions ...callopt.Option) (r *ucenter.AddressList, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAddress(ctx, Req)
}
