// Code generated by Kitex v0.10.3. DO NOT EDIT.

package member

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	ucenter "grpc_common/kitex_gen/ucenter"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"findMemberById": kitex.NewMethodInfo(
		findMemberByIdHandler,
		newFindMemberByIdArgs,
		newFindMemberByIdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	memberServiceInfo                = NewServiceInfo()
	memberServiceInfoForClient       = NewServiceInfoForClient()
	memberServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return memberServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return memberServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return memberServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Member"
	handlerType := (*ucenter.Member)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "ucenter",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.10.3",
		Extra:           extra,
	}
	return svcInfo
}

func findMemberByIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(ucenter.MemberReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(ucenter.Member).FindMemberById(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FindMemberByIdArgs:
		success, err := handler.(ucenter.Member).FindMemberById(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FindMemberByIdResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFindMemberByIdArgs() interface{} {
	return &FindMemberByIdArgs{}
}

func newFindMemberByIdResult() interface{} {
	return &FindMemberByIdResult{}
}

type FindMemberByIdArgs struct {
	Req *ucenter.MemberReq
}

func (p *FindMemberByIdArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(ucenter.MemberReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *FindMemberByIdArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *FindMemberByIdArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *FindMemberByIdArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FindMemberByIdArgs) Unmarshal(in []byte) error {
	msg := new(ucenter.MemberReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FindMemberByIdArgs_Req_DEFAULT *ucenter.MemberReq

func (p *FindMemberByIdArgs) GetReq() *ucenter.MemberReq {
	if !p.IsSetReq() {
		return FindMemberByIdArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FindMemberByIdArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FindMemberByIdArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FindMemberByIdResult struct {
	Success *ucenter.MemberRes
}

var FindMemberByIdResult_Success_DEFAULT *ucenter.MemberRes

func (p *FindMemberByIdResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(ucenter.MemberRes)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *FindMemberByIdResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *FindMemberByIdResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *FindMemberByIdResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FindMemberByIdResult) Unmarshal(in []byte) error {
	msg := new(ucenter.MemberRes)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FindMemberByIdResult) GetSuccess() *ucenter.MemberRes {
	if !p.IsSetSuccess() {
		return FindMemberByIdResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FindMemberByIdResult) SetSuccess(x interface{}) {
	p.Success = x.(*ucenter.MemberRes)
}

func (p *FindMemberByIdResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FindMemberByIdResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) FindMemberById(ctx context.Context, Req *ucenter.MemberReq) (r *ucenter.MemberRes, err error) {
	var _args FindMemberByIdArgs
	_args.Req = Req
	var _result FindMemberByIdResult
	if err = p.c.Call(ctx, "findMemberById", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
