// Code generated by Kitex v0.10.3. DO NOT EDIT.

package register

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	ucenter "grpc_common/kitex_gen/ucenter"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	RegisterByPhone(ctx context.Context, Req *ucenter.RegReq, callOptions ...callopt.Option) (r *ucenter.RegRes, err error)
	SendCode(ctx context.Context, Req *ucenter.CodeReq, callOptions ...callopt.Option) (r *ucenter.NoRes, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRegisterClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRegisterClient struct {
	*kClient
}

func (p *kRegisterClient) RegisterByPhone(ctx context.Context, Req *ucenter.RegReq, callOptions ...callopt.Option) (r *ucenter.RegRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RegisterByPhone(ctx, Req)
}

func (p *kRegisterClient) SendCode(ctx context.Context, Req *ucenter.CodeReq, callOptions ...callopt.Option) (r *ucenter.NoRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendCode(ctx, Req)
}
