// Code generated by Kitex v0.10.3. DO NOT EDIT.

package register

import (
	server "github.com/cloudwego/kitex/server"
	ucenter "grpc_common/kitex_gen/ucenter"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler ucenter.Register, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
