// Code generated by hertz generator.

package main

import (
	"exchange_api/config"
	"exchange_api/rpc"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/kitex/pkg/klog"
	"github.com/kitex-contrib/obs-opentelemetry/logging/zap"
	"os"
)

func main() {
	// 启动rpc服务
	rpc.Init()

	// 日志注册
	klog.SetLogger(zap.NewLogger())
	klog.SetLevel(klog.LevelDebug)
	f, err := os.OpenFile("./log/output.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		panic(err)
	}
	defer f.Close()
	klog.SetOutput(f)

	// 启动http服务
	h := server.Default(server.WithHostPorts(config.ServerAddr))

	register(h)
	h.Spin()
}
