// Code generated by hertz generator.

package model

import (
	"context"
	model "ucenter_api/biz/model"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Register .
// @router /uc/register/phone [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.Request
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(model.Response)

	c.JSON(consts.StatusOK, resp)
}

// SendCode .
// @router /uc/mobile/code [POST]
func SendCode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.CodeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(model.Response)

	c.JSON(consts.StatusOK, resp)
}
