// Code generated by hertz generator.

package handler

import (
	"common/results"
	"common/tools"
	"context"
	"github.com/cloudwego/kitex/pkg/kerrors"
	"github.com/jinzhu/copier"
	"grpc_common/kitex_gen/ucenter"
	"ucenter_api/config"
	"ucenter_api/rpc"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	model "ucenter_api/biz/model"
)

// Login .
// @router /uc/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.LoginReq
	err = c.BindAndValidate(&req)
	ip := tools.GetRemoteClientIp(c)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	loginReq := new(ucenter.LoginReq)
	copier.Copy(loginReq, &req)
	loginReq.Ip = ip
	data, err := rpc.GetLoginClient().Login(ctx, loginReq)
	if err != nil {
		results.NewResult().Deal(nil, err, c)
		return
	}
	resp := new(model.LoginRes)
	copier.Copy(resp, data)

	results.NewResult().Deal(resp, err, c)
}

func CheckLogin(ctx context.Context, c *app.RequestContext) {
	token := string(c.GetHeader("x-auth-token"))

	_, err := tools.ParseToken(token, config.AccessSecret)
	if err != nil {
		results.NewResult().Deal(false, kerrors.NewBizStatusError(-1, "验证不通过"), c)
	}
	results.NewResult().Deal(true, nil, c)
}
