// Code generated by hertz generator.

package model

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _marketMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _coininfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _symbolinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _symbolthumbMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _symbolthumbtrendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _exchange_rateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usdMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getusdrateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _historyMw() []app.HandlerFunc {
	// your code...
	return nil
}
