// Code generated by hertz generator.

package handler

import (
	"common/results"
	"context"
	"grpc_common/kitex_gen/market"
	"market_api/rpc"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	model "market_api/biz/model"
)

// GetUsdRate .
// @router /market/exchange-rate/usd/:unit [POST]
func GetUsdRate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.RateRequest
	err = c.BindPath(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	usdRate, err := rpc.GetExchangeRateClient().UsdRate(ctx, &market.RateReq{
		Unit: req.Unit,
	})
	if err != nil {
		results.NewResult().Deal(nil, err, c)
		return
	}
	resp := &market.RateRes{
		Rate: usdRate.Rate,
	}
	results.NewResult().Deal(resp, nil, c)
}
