// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/network/standard"
	"market_api/config"
	"market_api/processor"
	"market_api/ws"
)

func main() {
	h := server.New(server.WithHostPorts(config.ServerAddr), server.WithTransport(standard.NewTransporter))
	w := ws.NewWebSocketServer()
	go w.Start()
	defer w.Stop()
	register(h, w)
	p := processor.GetDefaultProcessor()
	p.Init(processor.NewWebsocketHandler(w))
	h.Spin()
}
