// Code generated by hertz generator. DO NOT EDIT.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	router "market_api/biz/router"
	"market_api/ws"
)

// register registers all routers.
func register(r *server.Hertz, ws *ws.WebSocketServer) {

	router.GeneratedRegister(r, ws)

	customizedRegister(r)
}
